name: Bash Tests
run-name: Testing ${{ github.repository }} by @${{ github.actor }}

on:
  push:
  workflow_dispatch:

env:
  TASK: hello

jobs:
  buildtest:
    name: BuildTest

    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Download tests
        uses: actions/checkout@v4
        with:
          repository: ITMO-OS-LITE/public-tests
          ref: master

      - name: Download student solutions
        uses: actions/checkout@v4
        with:
          path: src
          ref: master

      - name: Test solution
        shell: bash
        run: |
          ls -al
          ls -al src/
          python3 tmain.py --suite ${{ env.TASK }}
